In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [3]:
grid = np.array( [ [9, 8, 7],
                  [6, 5, 4] ] )

grid

array([[9, 8, 7],
       [6, 5, 4]])

In [4]:
y = np.array( [ [99],
               [99] ] )

y

array([[99],
       [99]])

In [5]:
np.vstack( [ x, grid ] )

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [6]:
np.vstack( [ grid, x ] )

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [7]:
np.vstack( [ grid, y ] )

'''
#It will give error because, to get appended the shape of y must be same as grid.
y shape is 2, 1 and grid shape is 3, 3 whereas, x shape is 1, 3

For vstack, col must be same and for hstack row must be same
'''

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [8]:
np.vstack( [ y, grid ] )

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [9]:
np.hstack( [ grid, y ] )

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [10]:
np.hstack( [ y,grid ] )

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [11]:
print( "For Horizontal Stack rows must be same ." )
print( "For Vertical Stack cols must be same ." )
print()
print( f"y.shape = { y.shape }, row in y = { y.shape[0] }, col in y = { y.shape[1] }" )
print( f"X.shape = { x.shape }, row in x = { y.shape[0] }" )
print( f"grid.shape = { grid.shape }, row in grid = { grid.shape[0] }, col in grid = { grid.shape[1] }" )

For Horizontal Stack rows must be same .
For Vertical Stack cols must be same .

y.shape = (2, 1), row in y = 2, col in y = 1
X.shape = (3,), row in x = 2
grid.shape = (2, 3), row in grid = 2, col in grid = 3


In [12]:
#Now, we will make a program to identify/ check where hstack or vstack is possible between 2 numpy arrays or not.

In [1]:
def stack_check( a, b, stack_op ):
    
    if( ( stack_op == 'h' or stack_op == 'H' ) ):
        if( ( a.shape[0] == b.shape[0]) ):
            return True
        
        return False
    
    elif( stack_op == 'v' or stack_op == 'V'):
        if( len(a.shape) == 1 ):
            if( ( a.shape[0] == b.shape[1]) ):
                return True

            return False
        
        else:
            if( ( a.shape[1] == b.shape[1]) ):
                return True

            return False

In [2]:
a = stack_check( x, y, 'v' )
a

NameError: name 'x' is not defined