In [1]:
'''Things going to be covered, 
1) full   -> To fill Custom value of any data type.
2) ones   -> To fill 1. value
3) zeros   -> To fill 0. value
4) eye   -> Identity Matrix
5) random.random  -> To fill random values/ numbers from 0 to 1
'''

'Things going to be covered, \n1) full   -> To fill Custom value of any data type.\n2) ones   -> To fill 1. value\n3) zeros   -> To fill 0. value\n4) eye   -> Identity Matrix\n5) random.random  -> To fill random values/ numbers from 0 to 1\n'

In [2]:
import numpy as np

In [26]:
#fill - To fill the array with same elements( Ex :- fill the array elements as 7 everywhere in array )
#full() :- np.full( dim, value )

arr7 = np.full( (3, 2, 3), 8 )
print( arr7 )

[[[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]]


In [27]:
#fill - To fill the array with same elements( Ex :- fill the array elements as 7.6 everywhere in array )
arr7point6 = np.full( (2, 4), 7.6 )
print( arr7point6 )
print()
arrone = np.full( (2, 4), 'Hi' )
print(arrone)

[[7.6 7.6 7.6 7.6]
 [7.6 7.6 7.6 7.6]]

[['Hi' 'Hi' 'Hi' 'Hi']
 ['Hi' 'Hi' 'Hi' 'Hi']]


In [28]:
#zeros - To fill the array with 0( Ex :- fill the array elements as 0 everywhere in array )
#zeros :- np.zeros( dim )

arr0 = np.zeros( (2, 4) )
print( arr0 )
print()
arr0 = np.full( (2, 4), 0. )
print( arr0 )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
#ones - To fill the array with 1( Ex :- fill the array elements as 1 everywhere in array )
#zeros :- np.ones( dim )

arr1 = np.ones( (2, 4) )
print( arr1 )
print()
arr1 = np.full( (2, 4), 1. )
print( arr1 )

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
#eye - To fill the array with digonal as 1( Ex :- fill the array elements digonally as 1 and others as 0 in array )

#Syntax :- np.eye( dim )

arreye = np.eye( 5 )    #Only Single '()' bracket. No double bracket like fill, zeros and ones
print( arreye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [54]:
#random.random - To fill the array with random number form 0 to 1
#Syntax :- np.random.random( dim )

arrrandom = np.random.random( (2, 4) )
print( f"arrrandom :- \n{ arrrandom }\n" )

#Syntax :- np.random.randint( range1, range2, dim )

n1 = np.random.randint( 2, 10, 4 )
n2 = np.random.randint( 12, 20, 4 )
n3 = np.random.randint( 22, 30, (4, 3) )

print( f"n1 :- \n{ n1 }\n" )
print( f"n2 :- \n{ n2 }\n" )
print( f"n3 :- \n{ n3 }\n" )

arrrandom :- 
[[0.79942014 0.1388789  0.99205714 0.93809865]
 [0.32377777 0.23848279 0.38480726 0.98546826]]

n1 :- 
[9 2 7 7]

n2 :- 
[12 14 15 13]

n3 :- 
[[23 22 27]
 [28 23 23]
 [26 27 25]
 [26 25 25]]



In [60]:
#Syntax :- np.random.seed( seed_value )
print( f"1. Without Seed, np.random.randint( 2, 10, 4 ) = { np.random.randint( 2, 10, 4 ) }")
print( f"2. Without Seed, np.random.randint( 2, 10, 4 ) = { np.random.randint( 2, 10, 4 ) }")
print( f"3. Without Seed, np.random.randint( 2, 10, 4 ) = { np.random.randint( 2, 10, 4 ) }")

1. Without Seed, np.random.randint( 2, 10, 4 ) = [9 4 3 6]
2. Without Seed, np.random.randint( 2, 10, 4 ) = [3 6 7 7]
3. Without Seed, np.random.randint( 2, 10, 4 ) = [5 7 9 4]


In [106]:
np.random.seed( 234234 )
print( f"4. With Seed, np.random.randint( 2, 10, 4 ) = { np.random.randint( 2, 10, (4, 100, 2, 5) ) }")

4. With Seed, np.random.randint( 2, 10, 4 ) = [[[[7 2 3 6 3]
   [2 6 3 8 3]]

  [[6 9 4 8 2]
   [8 3 9 3 6]]

  [[6 7 9 7 6]
   [6 8 2 2 8]]

  ...

  [[7 7 4 8 7]
   [7 7 8 9 2]]

  [[7 2 3 8 2]
   [6 2 3 7 9]]

  [[9 7 5 5 4]
   [2 3 8 2 2]]]


 [[[4 7 7 8 5]
   [7 5 7 5 7]]

  [[9 3 5 9 3]
   [8 5 8 4 2]]

  [[8 5 2 4 6]
   [6 9 7 3 5]]

  ...

  [[7 2 9 7 5]
   [9 7 6 8 9]]

  [[8 7 4 2 9]
   [9 2 6 4 3]]

  [[8 6 9 8 8]
   [6 8 4 9 4]]]


 [[[2 6 7 3 3]
   [2 3 8 4 7]]

  [[8 5 8 9 4]
   [7 6 5 7 2]]

  [[5 5 8 4 2]
   [7 9 8 5 8]]

  ...

  [[7 3 9 9 6]
   [5 8 3 3 6]]

  [[8 6 6 8 5]
   [2 7 9 8 6]]

  [[9 3 4 5 7]
   [4 9 3 5 4]]]


 [[[9 9 2 8 6]
   [4 5 2 3 2]]

  [[2 4 9 9 3]
   [3 3 5 7 9]]

  [[5 8 8 6 2]
   [6 3 7 2 9]]

  ...

  [[9 9 5 4 9]
   [2 6 2 8 7]]

  [[6 3 6 4 6]
   [4 2 3 5 4]]

  [[6 9 9 2 9]
   [7 7 3 8 8]]]]


In [103]:
print( f"5. Without Seed, np.random.randint( 2, 10, 4 ) = { np.random.randint( 2, 10, 4 ) }")

print( f"6. With Seed, np.random.randint( 2, 10, 4 ) = { np.random.randint( 2, 10, 4 ) }")

print( f"7. With Seed, np.random.randint( 2, 10, 4 ) = { np.random.randint( 2, 10, 4 ) }")

5. Without Seed, np.random.randint( 2, 10, 4 ) = [3 2 6 3]
6. With Seed, np.random.randint( 2, 10, 4 ) = [8 3 6 9]
7. With Seed, np.random.randint( 2, 10, 4 ) = [4 8 2 8]
