In [1]:
import numpy as np

In [12]:
x = np.arange( 1, 11 )
y = np.arange( 11, 26 )

In [13]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [15]:
#How MeshGrid Works,
"""
It will count the number of elements( 'n' ) inside a numpy array( 'aar1' ) and then, append the whole numpy array into a 
new numpy array( 'aar2'),
As New Array( 'arr2' ) = old_array('arr1') * no_of_elements in old_array( 'n' )
"""

"\nIt will count the number of elements( 'n' ) inside a numpy array( 'aar1' ) and then, append the whole numpy array into a \nnew numpy array( 'aar2'),\nAs New Array( 'arr2' ) = old_array('arr1') * no_of_elements in old_array( 'n' )\n"

In [17]:
np.meshgrid( x, y )

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
        [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
        [13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
        [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
        [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]

In [18]:
np.meshgrid( y, x )

[array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]]),
 array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,  5,  

In [19]:
"""
linespace will make a numpy array starts from starting point and ENds as ending point in that It will for increment rate 
    between starting to Ending range.
    elements will having variation of ( End - Start ) / increment_rate 
"""

x = np.linspace( 0, 5, 10 )
y = np.linspace( 5, 10, 10 )

In [20]:
"""
Ex :- First Element is starting at 0. and End is 5. Where are each elemtent is increasing by 0.55555556
"""

x

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
"""
Ex :- First Element is starting at 5. and End is 9. Where are each elemtent is increasing by 0.44444444
"""

y

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [22]:
x_mesh, y_mesh = np.meshgrid( x, y )

In [23]:
x_mesh

array([[0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
       [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
       [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
       [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
       [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
       [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
       [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
       [0.        , 0.55555556, 1.1111111

In [24]:
y_mesh

array([[ 5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
         5.        ,  5.        ,  5.        ,  5.        ,  5.        ],
       [ 5.55555556,  5.55555556,  5.55555556,  5.55555556,  5.55555556,
         5.55555556,  5.55555556,  5.55555556,  5.55555556,  5.55555556],
       [ 6.11111111,  6.11111111,  6.11111111,  6.11111111,  6.11111111,
         6.11111111,  6.11111111,  6.11111111,  6.11111111,  6.11111111],
       [ 6.66666667,  6.66666667,  6.66666667,  6.66666667,  6.66666667,
         6.66666667,  6.66666667,  6.66666667,  6.66666667,  6.66666667],
       [ 7.22222222,  7.22222222,  7.22222222,  7.22222222,  7.22222222,
         7.22222222,  7.22222222,  7.22222222,  7.22222222,  7.22222222],
       [ 7.77777778,  7.77777778,  7.77777778,  7.77777778,  7.77777778,
         7.77777778,  7.77777778,  7.77777778,  7.77777778,  7.77777778],
       [ 8.33333333,  8.33333333,  8.33333333,  8.33333333,  8.33333333,
         8.33333333,  8.33333333,  8.33333333