In [2]:
'''Things to be covered,

1) Declaring Numpy arrays,
2) Finding the Shape of Numpy Arrays
3) Checking Mutability
'''

'Things to be covered,\n\n1) Declaring Numpy arrays,\n2) Finding the Shape of Numpy Arrays\n3) Checking Mutability\n'

In [4]:
import numpy as np

In [12]:
#Single Dimension Array
l = [1, 12, 0, 4]

arr = np.array( l )

print(f"l = { l }\n")
print(f"arr = { arr }" )

l = [1, 12, 0, 4]

arr = [ 1 12  0  4]


In [13]:
#syntax :- np.array( list )

print( f"type(l) = { type(l) }" )
print( f"type( arr ) = { type( arr ) }\n" )

print( f"len(l) = { len(l) }" )
print( f"len(arr) = { len(arr) }" )

print( arr.shape )
print( f"This is Numpy Array = { arr }" )
print( f"This is list = { l }" )

type(l) = <class 'list'>
type( arr ) = <class 'numpy.ndarray'>

len(l) = 4
len(arr) = 4
(4,)
This is Numpy Array = [ 1 12  0  4]
This is list = [1, 12, 0, 4]


In [14]:
#Printing the elements of array
for i in arr:
    print(i, end = ', ')

1, 12, 0, 4, 

In [15]:
#Changing the elements of array using indexes( Mutability )
print( arr )

arr[2] = 20

print( arr )

[ 1 12  0  4]
[ 1 12 20  4]


In [16]:
arr

array([ 1, 12, 20,  4])

In [29]:
#Multi Dimensional Array

arr = np.array( [ [1, 12, 0, 4], [8, 1, 5, 0] ] )   #Unequal Number of elements in nested array.
print( arr )
print( f"arr.shape = { arr.shape }" )

[[ 1 12  0  4]
 [ 8  1  5  0]]
arr.shape = (2, 4)


In [30]:
'''
#Multi Dimensional Array
arr = np.array( [ [1, 12, 0, 4], [8, 1, 5, 0] ] )   #Equal Number of elements in nested array.
print( f"arr = {arr}" )
print( f"len(arr) = {len(arr)}" )

print( f"arr.shape = { arr.shape }" )
'''

'''
#Multi Dimensional List

l = [ [ [1, 2, 3, 4, 5], 6, 9, 10], [10, 11, 19, 34] ]
print(l)

print()
arr2 = np.array( l )
print( arr2 )   
print( arr2.shape )
'''

'''
How numpy works internally.
np.array( [ [ [1, 2, 3, 4, 5], 6, 9, 10],
            [10, 11, 19, 34] ] )
'''

'\nHow numpy works internally.\nnp.array( [ [ [1, 2, 3, 4, 5], 6, 9, 10],\n            [10, 11, 19, 34] ] )\n'

In [31]:
print( arr )
print()
print( arr.shape )

[[ 1 12  0  4]
 [ 8  1  5  0]]

(2, 4)


In [32]:
a, b = 2, 3
print(f"a  = { a } and b = { b }")

print( arr2 )
print()
print(f"arr.shape = { arr2.shape }")

row, col = arr2.shape

print(f"No. of Rows = {row} and No. of Columns = {col}")

a  = 2 and b = 3
[[list([1, 2, 3, 4, 5]) 6 9 10]
 [10 11 19 34]]

arr.shape = (2, 4)
No. of Rows = 2 and No. of Columns = 4


In [33]:
#Printing the elements of array
count = 1

for i in arr:    #i = [1 12 0 4] -> [8 1 5 0]
    print(f"Row {count} : ", end = '')
    print(i)
    
    for j in i:
        print(f"j = {j}")
    count += 1

print( f"count = { count }" )

Row 1 : [ 1 12  0  4]
j = 1
j = 12
j = 0
j = 4
Row 2 : [8 1 5 0]
j = 8
j = 1
j = 5
j = 0
count = 3


In [35]:
#Changing the elements of array using indexes( Mutability )
print("old arr :- ")
print(arr)
print()
print( f"arr[0] = { arr[0] }" )
print( f"arr[0][1] = { arr[0][1] }" )
print()

arr[0][2] = 1
arr[1][2] = 2
print("New arr :- ")
print( arr )

old arr :- 
[[ 1 12  1  4]
 [ 8  1  2  0]]

arr[0] = [ 1 12  1  4]
arr[0][1] = 12

New arr :- 
[[ 1 12  1  4]
 [ 8  1  2  0]]
