In [1]:
import numpy as np

In [2]:
l = [5, 9, 10, 8]
print( l )

arr = np.array( l )
print(arr)

[5, 9, 10, 8]
[ 5  9 10  8]


In [7]:
print( f"np.arange(3) = { np.arange(3) }")
print()
print( f"np.arange( start = 3 ) = { np.arange( start = 3 ) }" )
print()
print( f"np.arange(3.0) = { np.arange(3.0) }" )
print()
print( f"np.arange(3.2) = { np.arange(3.2) }" )
print()
print( f"np.arange(3,7.000001) = { np.arange(3, 7.000001) }" )
print()
print( f"np.arange(start = 3, stop = 7.1)  = { np.arange(start = 3, stop = 7.1) }" )
print()
print( f"np.arange(3, 7.1, 2) = { np.arange(3, 7.1, 2) }" )
print()
print( f"np.arange(start = 3, stop = 7.1, step = 2)  = { np.arange(start = 3, stop = 7.1, step = 2) }" )
print()
print( f"np.array( list( range(3, 7, 2) ) ) = { np.array( list( range(3, 7, 2) ) ) }" )

np.arange(3) = [0 1 2]

np.arange( start = 3 ) = [0 1 2]

np.arange(3.0) = [0. 1. 2.]

np.arange(3.2) = [0. 1. 2. 3.]

np.arange(3,7.000001) = [3. 4. 5. 6. 7.]

np.arange(start = 3, stop = 7.1)  = [3. 4. 5. 6. 7.]

np.arange(3, 7.1, 2) = [3. 5. 7.]

np.arange(start = 3, stop = 7.1, step = 2)  = [3. 5. 7.]

np.array( list( range(3, 7, 2) ) ) = [3 5]


In [8]:
print( np.array( list( range( 10, 1, -2 ) ) ) )

[10  8  6  4  2]


In [9]:
print( np.arange( 10, 1, -2 ) )

[10  8  6  4  2]


In [14]:
arr1 = np.arange( 1, 13 )
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
arr1 = arr1.reshape( (3, 4) )
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr1 = arr1.ravel()
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
arr1 = arr1.reshape( (2, 6) )
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
arr1 = arr1.ravel()
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
arr1 = arr1.reshape( (4, 3) )
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
arr1 = arr1.ravel()
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
arr1 = arr1.reshape( (6, 2) )
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [27]:
arr1 = arr1.ravel()
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
#How to know posible reshapes dimension of any numpy array ?

In [29]:
arr_len = len( arr1 )
arr_len

12

In [33]:
dimension = []

for i in range( 1, arr_len + 1 ):
    
    if( (arr_len%i) == 0 ):
        temp = []
        temp.append( i )
        temp.append( arr_len//i )
        dimension.append( temp )

print( dimension )

[[1, 12], [2, 6], [3, 4], [4, 3], [6, 2], [12, 1]]


In [34]:
for i in dimension:
    print(i)

[1, 12]
[2, 6]
[3, 4]
[4, 3]
[6, 2]
[12, 1]


In [35]:
for i in dimension:
    
    print( arr1.reshape( ( i[0], i[1] ) ) )
    print()

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

