In [1]:
import numpy as np

In [2]:
#Sorting

unsorted = np.random.rand( 2, 4 )   #It makes 2 list and put both into an another list
#( n, e ) -> n is number of list and e is number of elements in each list. 
print( unsorted )
print()
print( type( unsorted ) )
unsorted.sort()                 #Our nd array is now sorted.
print()
print( unsorted )

[[0.43155701 0.20808517 0.27203022 0.08058715]
 [0.97120112 0.38068888 0.03256523 0.65781368]]

<class 'numpy.ndarray'>

[[0.08058715 0.20808517 0.27203022 0.43155701]
 [0.03256523 0.38068888 0.65781368 0.97120112]]


In [7]:
#unique() - Will remove the duplicates.

arr1 = np.array( [1, 2, 3, 3, 9, 1, 2] )
print( np.unique( arr1 ) )

[1 2 3 9]


In [8]:
#intersection of 2 arrays.

arr2 = [3, 9, 10, 11, 10, 14]

print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )
print()
print( f"np.intersect1d( arr1, arr2 ) = { np.intersect1d( arr1, arr2 ) }" )
print()
print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]

np.intersect1d( arr1, arr2 ) = [3 9]

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]


In [6]:
#Union of 2 arrays.

arr2 = [3, 9, 10, 11, 10, 14]

print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )
print()

print( np.union1d( arr1, arr2 ) )
print()
print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]

[ 1  2  3  9 10 11 14]

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]


In [7]:
#diifrence of 2 numpy arrays
print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )
print()
print( np.setdiff1d( arr1, arr2 ) )  #removes the common part of arr1 and arr2, and then, it shows arr1.
print()
print( f"arr1 = { arr1 }" )
print( f"arr2 = { arr2 }" )
print()
#print( arr1 - np.intersect1d( arr1, arr2 ) )

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]

[1 2]

arr1 = [1 2 3 3 9 1 2]
arr2 = [3, 9, 10, 11, 10, 14]



In [8]:
print( np.setdiff1d( arr2, arr1 ) )  #removes the common part of arr1 and arr2, and then, it shows arr2.

#arr2 - np.intersect1d( arr1, arr2 )

[10 11 14]


In [9]:
print( f"arr1 = { arr1 }" )
print()
print( f"arr2 = { arr2 }" )
print()
print( f"np.in1d( arr1, arr2 ) = { np.in1d( arr1, arr2 ) }" )
print()
print( f"arr1[ np.in1d( arr1, arr2 ) ] = arr1[ {np.in1d( arr1, arr2 )} ] = { arr1[ np.in1d( arr1, arr2 ) ] }" )
print()
print( f"np.in1d( arr2, arr1 ) = { np.in1d( arr2, arr1 ) }" )
print()
print( f"type( arr1 ) = { type( arr1 ) }" )
print( f"type( arr2 ) = { type( arr2 ) }" )
print()

arr1 = list( arr1 )
arr2 = np.array( arr2 )

print( f"arr2[ np.in1d( arr2, arr1 ) ] = arr2[ {np.in1d( arr2, arr1 ) } ] = { arr2[ np.in1d( arr2, arr1 ) ] }" )
print()

boolarr2 = np.in1d( arr2, arr1 )

print('[', end = ' ')

for i in range( len( boolarr2 ) ):
                if( boolarr2[i] == True ):
                    print( arr2[i], end = ' ' )
print(']')

#Conclusion :- np.in1d( numpy.array, list ) Otherwise, It will Give Error.

arr1 = [1 2 3 3 9 1 2]

arr2 = [3, 9, 10, 11, 10, 14]

np.in1d( arr1, arr2 ) = [False False  True  True  True False False]

arr1[ np.in1d( arr1, arr2 ) ] = arr1[ [False False  True  True  True False False] ] = [3 3 9]

np.in1d( arr2, arr1 ) = [ True  True False False False False]

type( arr1 ) = <class 'numpy.ndarray'>
type( arr2 ) = <class 'list'>

arr2[ np.in1d( arr2, arr1 ) ] = arr2[ [ True  True False False False False] ] = [3 9]

[ 3 9 ]
