In [1]:
import numpy as np

In [2]:
arr = np.array( [ list( range(0, 10, 3) ), list( range(10, 20, 3) ), list( range(20, 30, 3) ) ] )
print(arr)
print( type( arr ) )

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]
<class 'numpy.ndarray'>


In [8]:
#Method 1 :- 
print("Following is newarr1,")
newarr1 = arr > 13
print( newarr1 )
print()

#Method 2( Algorithm Based ) :- 
newarr2 = []

for i in arr:     #[0 3 6 9], [ 10 13 16 19 ]
    temp = []
    for j in i:   # 13
        temp.append( j > 13 )   #temp = [False, False, True, True]
    
    newarr2.append( temp )   #[], [ [False, False, False, False], [False, False, True, True], [True, True, True, True] ]
    
for i in newarr2:
    print(i)

#We can see the diffrence between newarr1 and newarr2. There is no comma(, ) between elements of newarr1(ndarray) whereas,
# in newarr2( list ) contains comma(, ) between the elements.
print()
print( f"type( newarr1 ) = { type( newarr1 ) }" )
print( f"type( newarr2 ) = { type( newarr2 ) }" )

newarr2 = np.array( newarr2 )

print()
print( newarr2 )
print()
print( f"type( newarr1 ) = { type( newarr1 ) }" )
print( f"type( newarr2 ) = { type( newarr2 ) }" )

Following is newarr1,
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

[False, False, False, False]
[False, False, True, True]
[True, True, True, True]

type( newarr1 ) = <class 'numpy.ndarray'>
type( newarr2 ) = <class 'list'>

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

type( newarr1 ) = <class 'numpy.ndarray'>
type( newarr2 ) = <class 'numpy.ndarray'>


In [11]:
#Selecting the value inside array 'arr' elements which are true and satisfies the condition

#Method 1 :-
print( arr )
print()
print( newarr1 )
print()
print(f"arr[ newarr1 ] = {arr[ newarr1 ]}" )
print(f"type( arr[newarr1] ) = { type( arr[newarr1] ) }" )
print()
#It will give error, print( arr[ newarr2 ] ) This Method1 is not possible with list.

#Method 2 :-
print( arr )
print()
print( newarr1 )
print()
l = []

print( f"len(arr) = { len(arr) }" )

for i in range( len( arr ) ):   #0, 1, 2
    templist = list( arr[i])  #arr[0] = [0 3 6 9] -> [0, 3, 6, 9]
    
    for j in range( len(templist) ): #0, 1, 2, 3  
        if( newarr1[i][j]):
            l.append( arr[i][j] )

print(f"l = {l}")  #We have the data but, we can't access data using list in numpy. we must convert the list into ndarray.
#If we convert list into ndarray then, it give  4> dimensional and more depends on dimension of list.
print( f"type( l ) = { type( l ) }" )
print()
l = np.array( l )
print( f"l = { l }")
print( f"type( l ) = { type( l ) }" )

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

arr[ newarr1 ] = [16 19 20 23 26 29]
type( arr[newarr1] ) = <class 'numpy.ndarray'>

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

len(arr) = 3
l = [16, 19, 20, 23, 26, 29]
type( l ) = <class 'list'>

l = [16 19 20 23 26 29]
type( l ) = <class 'numpy.ndarray'>


In [12]:
print( f"arr[ arr>15 ] = {arr[ arr>15 ]}" )
print()
print( arr )
print()
print( arr>10 )
print()
print( arr<20 )
print()
print( (arr>10) & (arr <20) )
print()
print( arr[ (arr>10) & (arr <20) ] )   #arr[0], arr[ new_arr ]
#In python we write, print( arr[ (arr>10) and (arr <20) ] ) but here instead of and Logical operator, we are using '&' .

arr[ arr>15 ] = [16 19 20 23 26 29]

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]

[[False False False False]
 [False  True  True  True]
 [False False False False]]

[13 16 19]


In [13]:
print( arr )
print()
print(f"arr[ arr%2 == 0 ] = {arr[ arr%2 == 0 ]}")

arr[ arr%2 == 0 ] = arr[ arr%2 == 0 ] + 2
print()
print( arr )

[[ 0  3  6  9]
 [10 13 16 19]
 [20 23 26 29]]

arr[ arr%2 == 0 ] = [ 0  6 10 16 20 26]

[[ 2  3  8  9]
 [12 13 18 19]
 [22 23 28 29]]
