In [1]:
#Why Standard Scaler ?

#Ans : #StandardScaler will normalize our Data. Basically we use it reduce the variation between one element of array
#and 2nd element of array

In [2]:
import numpy as np

In [9]:
x = np.array( [ [ 40, 50, -20, 45, -90, 24 ] ] )

In [10]:
print( x )
print( type(x) )

[[ 40  50 -20  45 -90  24]]
<class 'numpy.ndarray'>


In [11]:
x.mean()

8.166666666666666

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
ssc = StandardScaler()

In [14]:
x = ssc.fit_transform( x )

In [15]:
x

array([[0., 0., 0., 0., 0., 0.]])

In [16]:
#Standard Scaller will always work with multidimensional Array.

In [18]:
x = np.array( [ [40], [42], [43], [45], [-90], [24] ] )

l1 = [20, 10, 30]
l2 = [40, 50, 60]

y = np.array( [ l1, l2 ] )
print( x )
print()
print(y)

[[ 40]
 [ 42]
 [ 43]
 [ 45]
 [-90]
 [ 24]]

[[20 10 30]
 [40 50 60]]


In [20]:
temp_x = x.copy()

In [21]:
x = ssc.fit_transform( x )

In [22]:
print( x )
print()
print( temp_x )

[[ 0.46738983]
 [ 0.50863011]
 [ 0.52925025]
 [ 0.57049053]
 [-2.21322831]
 [ 0.1374676 ]]

[[ 40]
 [ 42]
 [ 43]
 [ 45]
 [-90]
 [ 24]]


In [24]:
temp_x.mean()

17.333333333333332

In [25]:
#Formula for Standard Scaler is :- 

#xi = ( Xi - X_mean )/ ( Standard Deviation )

#To Find Standard Deviation.

print( f"standar deviation = np.std( x ) = { np.std( temp_x ) }" )
print( f"Mean of X = np.mean( x ) = { np.mean( temp_x ) }" )

standar deviation = np.std( x ) = 48.496277062150746
Mean of X = np.mean( x ) = 17.333333333333332


In [26]:
print( ( 42-17.333333333333332 )/ 48.496277062150746 )

0.5086301085556512


In [27]:
#We can See, the above value is same as y[0], y[1], y[2]

In [28]:
#Now, Dealing With DataSet

In [29]:
import pandas as pd

In [30]:
data = pd.read_csv('Data.csv')

In [31]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [37]:
x = data.loc[ : , 'Age' : 'Salary' ]
x.head()

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
ssc = StandardScaler()

In [40]:
y = ssc.fit_transform( x )

In [42]:
y

array([[ 0.71993143,  0.71101276],
       [-1.62367514, -1.36437583],
       [-1.21009751, -0.84552869],
       [-0.10722383, -0.24020701],
       [ 0.16849459,         nan],
       [-0.52080146, -0.49963059],
       [        nan, -1.01847774],
       [ 1.27136827,  1.31633443],
       [ 1.54708669,  1.66223253],
       [-0.24508304,  0.27864014]])

In [43]:
y = pd.DataFrame( y )
y

0         1
0  0.719931  0.711013
1 -1.623675 -1.364376
2 -1.210098 -0.845529
3 -0.107224 -0.240207
4  0.168495       NaN
5 -0.520801 -0.499631
6       NaN -1.018478
7  1.271368  1.316334
8  1.547087  1.662233
9 -0.245083  0.278640

In [44]:
y.isnull().sum()

0    1
1    1
dtype: int64

In [46]:
y = y.fillna( 0)

In [47]:
y

0    0.719931
1   -1.623675
2   -1.210098
3   -0.107224
4    0.168495
5   -0.520801
6    0.000000
7    1.271368
8    1.547087
9   -0.245083
Name: 0, dtype: float64